# Netlify configuration file

[build]
  command = "sed -i 's|__SCRIPT_URL__|'${SCRIPT_URL}'|g' script.js"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true